### PR TITLE
fall cleanup / code review

### PR DESCRIPTION
**Pull request by carlbordum**
Hi there, great project.

I did a few things for consistency:
* changed the `"` strings to `'`
* added dots in docstrings
* cut long lines

Furthermore I made `show_news`read a bit nicer (in my opinion) and made usage of the `requests`-api proper.

Let me know if I did anything you dislike :)

### CODE REVIEW

**Comment by shivam043** [comment]
Thanks @Zaab1t  for appreciating the project.
Changes which you are proposing are not necessary,it will be highly appreciated if you can propose a new feature to the project.
Thanks

**Comment by carlbordum** [comment]
I forgot to mention two things:
* removed unused function `check_choice`
* fixed bug in `show news` where it didnt stop if `choice == 'n'`

**Comment by shivam043** [comment]
Its not a bug it's working fine,you can see in the code we are looping until while loop is 'y',when it becomes 'n',it will exit @Zaab1t

**Comment by carlbordum** [comment]
Oh yeah, my bad. I guess line 138 - 141 doesn't really do anything.

**Pull request closed without merging**
